In [33]:
import numpy as np

In [34]:
arr1 = np.array([1, 2,3, 4, 5, 6])
print(arr1)


[1 2 3 4 5 6]


In [36]:
arr1.ndim

1

In [37]:
print(np.__version__)

1.20.1


In [38]:
print(type(arr1))

<class 'numpy.ndarray'>


# 1D

In [39]:
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

[1 2 3 4 5]


# 2d

In [40]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [41]:
arr2.ndim

2

In [42]:
arr2_1 = np.array([[1, 2, 3], [4, 5, 6],[7,10,12]])
print(arr2_1)
print(arr2_1.ndim)
arr2_1.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7 10 12]]
2


(3, 3)

In [43]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6],[1, 2, 3], [4, 5, 6]]])
print(arr2)
print(arr2.ndim)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
3


In [44]:
q = np.array([[[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]],[[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]]])
q

array([[[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]]],


       [[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]]]])

In [45]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
print(b.shape)

c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)


d = np.array([[[1, 2, 3], [4, 5, 6],[3,3,5]], [[2, 4, 8], [3, 3, 5],[3,3,5]]])
print(d)
print(d.shape)
e = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) # displays number of dimensions
print(d)

print(c.shape)

(5,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1 2 3]
  [4 5 6]
  [3 3 5]]

 [[2 4 8]
  [3 3 5]
  [3 3 5]]]
(2, 3, 3)
0
1
2
3
[[[1 2 3]
  [4 5 6]
  [3 3 5]]

 [[2 4 8]
  [3 3 5]
  [3 3 5]]]
(2, 3)


In [46]:
print(d)
print(d.shape) # displays number of matrices, rows and columns

[[[1 2 3]
  [4 5 6]
  [3 3 5]]

 [[2 4 8]
  [3 3 5]
  [3 3 5]]]
(2, 3, 3)


In [47]:
e.size  # displays total number of values 

18

In [48]:
b.dtype

dtype('int32')

In [49]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Indexing
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [50]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [52]:
arr = np.array([1, 2, 3, 4,9,6,8,10])

print(arr[6])



8


In [53]:
arr = np.array([1, 2, 3, 4])

j = arr +2

print(arr + 2)

print(arr * 2)

print(arr[2] + arr[3])

print(j)

[3 4 5 6]
[2 4 6 8]
7
[3 4 5 6]


In [54]:
arr12 = np.array([3,4,6,7])
arr12

arr = np.array([1, 2, 3, 4])

arr12.dtype

print(arr + arr12)

print(arr *2 + arr12 *2)

ghy = arr + arr12
    
print(arr * arr12)
print(ghy)

[ 4  6  9 11]
[ 8 12 18 22]
[ 3  8 18 28]
[ 4  6  9 11]


Multi dimensional indexing

In [55]:
array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
array.ndim

2

In [56]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
array.shape

(2, 5)

In [60]:
## Finding 9

print(array[1,2])

print("Fourth value of second row is ", array[1,4])

8
Fourth value of second row is  10


In [61]:
## Access last elements 

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Last element from 2nd dim: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


In [62]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

# Find 5th value of second dimension
# Find 3rd element of 1st dimension
arr.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [63]:
arr[1,4]

arr[0,2]

3

In [ ]:
## Some Built-in functions of numpy

In [64]:
array = np.array([[10,16,3],[2,5,6]])
print(array)
array.ndim
array.dtype

[[10 16  3]
 [ 2  5  6]]


dtype('int32')

In [65]:
zeros = np.zeros((4,3),int)
zeros


np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [66]:
ones = np.ones((2,3),dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [67]:
identity_matrix = np.eye(4,5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [68]:
print(np.min(array))

np.median(array)

2


5.5

In [69]:
np.max(array)

16

In [70]:
np.sum(array)

42

In [71]:
np.mean(array)

7.0

In [72]:
np.sqrt(array)

array([[3.16227766, 4.        , 1.73205081],
       [1.41421356, 2.23606798, 2.44948974]])

In [73]:
np.reshape((array),(3,2))


array([[10, 16],
       [ 3,  2],
       [ 5,  6]])

In [74]:
rand_arr = np.random.rand(2,3) ## generates random uniform numbers within range of 0-1 of given shape, single float with no argument

randint_arr = np.random.randint(2, 10,size=(2,3)) 

print(rand_arr ,'\n\n')
randint_arr

[[0.76712432 0.91590597 0.45399646]
 [0.58932389 0.28808284 0.43601292]] 




array([[7, 3, 5],
       [6, 2, 2]])

In [75]:
arr = np.arange(2,14,2)
print(arr)

[ 2  4  6  8 10 12]


In [76]:
arr = np.array([1, 2, 3, 4, 5])

square = arr ** 2
square   

array([ 1,  4,  9, 16, 25], dtype=int32)

## Reshape
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [102]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
print(arr.shape)
newarr = arr.reshape(4, 3)

print(newarr)

(1, 12)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [103]:
newarr.shape

(4, 3)

In [82]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
print(arr.shape)
newarr = arr.reshape(2, 3, 2)

print(newarr)

(1, 12)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [4]:
import numpy as np
import pandas as pd

# Load dataset
file_path = r'C:\Users\Bilal Qaisar\Downloads\Span_new.csv'
data = pd.read_csv(file_path)


In [5]:
data

,Unnamed: 0,ID,make,model,months_old,power,gear,fuel_type,kms,price,age
0,0,97860,NaN,911,240.0,210.0,NaN,gasoline,202000,999999.0,1998.0
1,1,27821,NaN,Mustang,54.0,487.0,NaN,NaN,30000,685000.0,2013.0
2,1,27821,NaN,Mustang,54.0,487.0,NaN,NaN,30000,685000.0,2013.0
3,3,98251,NaN,911,14.0,368.0,NaN,gasoline,2800,470000.0,2016.0
4,3,98251,NaN,911,14.0,368.0,NaN,gasoline,2800,470000.0,2016.0
...,...,...,...,...,...,...,...,...,...,...,...
92380,93986,38173,Opel,Astra,NaN,52.0,manual,gasoline,134700,350.0,1995.0
92381,93987,57303,Volkswagen,Polo,NaN,37.0,manual,gasoline,67762,350.0,1998.0
92382,93988,14541,Bmw,320,NaN,125.0,manual,gasoline,200000,300.0,2002.0
92383,93989,103604,Seat,Toledo,NaN,66.0,manual,gasoline,196000,300.0,1995.0


# Convert relevant numerical columns to NumPy arrays

In [6]:
price_array = data['price'].to_numpy()
kms_array = data['kms'].to_numpy()
power_array = data['power'].to_numpy()
months_old_array = data['months_old'].to_numpy()
age_array = data['age'].to_numpy()

In [7]:
price_array

array([9.99999e+05, 6.85000e+05, 6.85000e+05, ..., 3.00000e+02,
       3.00000e+02, 2.00000e+02])

In [8]:
import numpy as np

In [9]:
print("Number of NaN values:", np.isnan(price_array).sum())

Number of NaN values: 1


In [10]:
print("Number of NaN values:", np.isnan(kms_array).sum())

Number of NaN values: 0


In [11]:
print("Number of NaN values:", np.isnan(power_array).sum())

Number of NaN values: 1


In [12]:
np.isnan(months_old_array).sum()

9

In [13]:
np.isnan(age_array).sum()

1

# Missing Values

In [14]:
print("Number of NaN values:", np.isnan(price_array).sum())

Number of NaN values: 1


In [32]:
print("Number of NaN values:", np.isnan(kms_array).sum())

Number of NaN values: 0


In [31]:
np.mean(price_array)

nan

In [23]:
np.isnan(price_array).sum()

1

# Replace Missing Values

In [16]:
price_array_no_nan = np.nan_to_num(price_array, nan=0)# Replace NaN with 0

In [17]:
price_array_no_nan

array([9.99999e+05, 6.85000e+05, 6.85000e+05, ..., 3.00000e+02,
       3.00000e+02, 2.00000e+02])

In [24]:
np.mean(price_array)

nan

# Replace NaN with the mean of non-NaN values

In [25]:
mean_value = np.nanmean(price_array)  # Calculate mean ignoring NaN

In [26]:
mean_value

16509.91353481122

In [27]:
price_array_filled = np.where(np.isnan(price_array), mean_value, price_array) # Replace NaN values with the mean

In [28]:
np.mean(price_array_filled)

16509.913534811225

# Basic Statistics

In [11]:
np.mean(price_array)

nan

In [15]:
print("Number of NaN values:", np.isnan(price_array).sum())

Number of NaN values: 1


In [29]:


print("Mean Price:", np.mean(price_array_filled))
print("Median Price:", np.median(price_array_filled))
print("Minimum Price:", np.min(price_array_filled))
print("Maximum Price:", np.max(price_array_filled))
print("Standard Deviation of Price:", np.std(price_array_filled))

Mean Price: 16509.913534811225
Median Price: 13345.0
Minimum Price: 200.0
Maximum Price: 999999.0
Standard Deviation of Price: 15594.705917422716


# Indexing and Slicing

In [30]:
print("First 5 Prices:", price_array_filled[:5])  
print("First 5 Kms:", kms_array[:5])

First 5 Prices: [999999. 685000. 685000. 470000. 470000.]
First 5 Kms: [202000  30000  30000   2800   2800]


# Filtering and Masking

In [ ]:

filtered_prices = price_array[price_array > 500000]
print("Prices Greater Than 500,000:", filtered_prices)

# Basic Element-wise Operations

In [ ]:
price_per_km = price_array / kms_array
print("Price Per Km Array:", price_per_km)

# Sorting

In [ ]:
sorted_kms = np.sort(kms_array)
print("Sorted Kms:", sorted_kms)